### ISSUE TITLE
Code 505 Error when updating mods

### ISSUE THREAD

**Issue by mjw210** [factoriotools/factorio-docker#273] opened 2019-07-05 10:40 UTC
Receiving a Code 505 error when a mod needs to be updated:

`Checking for update of mod bobgreenhouse...`
`  Already up-to-date.`
`Checking for update of mod bobinserters...`
`Downloading...`
`  Download failed: Code 505.`
`Checking for update of mod boblibrary...`
`  Already up-to-date.`

**Comment by SuperSandro2000** [comment] 2019-07-05 12:30
Thanks for the issue. The mod updater's release was a bit rushed and I will take a look at this the next days and fix it.

**Comment by SuperSandro2000** [comment] 2019-07-06 13:25
Can't reproduce that. Did you check if the token is correct?

**Comment by mjw210** [comment] 2019-07-06 13:44
Looks like I didn't match the case when using the variable TOKEN or USERNAME.  Resolving that seems to allow it to connect, but now I'm running into the issue where each file is giving me an SHA1 mismatch.  Log file attached.

[Factorio.txt](https://github.com/factoriotools/factorio-docker/files/3364714/Factorio.txt)

**Comment by SuperSandro2000** [comment] 2019-07-06 13:49
I already noticed this while testing and a fix for that will be pushed today. I close this for now. If you have any more trouble feel free to comment on this issue.

**Closed by SuperSandro2000** 2019-07-06 13:49 UTC
Labels: bug, mod updater, need more info

**Comment by MikeFranklinJ** [comment] 2019-07-06 13:59
I think the issue is either on the factorio end or your network.

assuming the webserver isn't lying 505 is a bad gateway so something might be broken in theirproducing. now what I think is happening is a auth error which redirects to a login page hence the mismatch.

can you update mods on the client and is the server on the same network?
has this recently stopped working?

**Comment by SuperSandro2000** [comment] 2019-07-06 14:40
I tested it with one mod today on the server and that worked. If the issue I would suggest your write Factorio support if it is happening on the web and in the game itself, too.

**Comment by mtibke** [comment] 2020-12-21 21:34
Just for the case that somebody else runs into the same issue again. For me this error was caused by a simple space at the end of the token within the server-settings.json file.
