### ISSUE TITLE
'stable' tag not following factorio.com

### ISSUE THREAD

**Issue by jlucktay** [factoriotools/factorio-docker#375] opened 2021-02-18 11:09 UTC
Hi there, and thank you for this image!
We use it on our server all the time, and have our setup tracking the `stable` tag.

However, when running up today and connecting, I saw an error that my client was `1.1.21` but the server was `1.1.25`.

The README here states that the `stable` tag is the version declared stable on [factorio.com](https://factorio.com), but when I checked there just now (18th Feb @ 11:09 UTC) it says that `1.1.21` is stable and that `1.1.25` is still experimental:

![image](https://user-images.githubusercontent.com/460028/108348125-48e8f280-71d9-11eb-81b2-eb0f9627df06.png)

Is this update done manually, or by some kind of automated mechanism?
Either way, can the versions be properly (re)aligned if at all possible?
Cheers, and thank you again! 🙏

**Comment by Wumfie** [comment] 2021-02-19 15:14
I think the server gets the update before the game does. Just wait for 1.1.25 to be sent to your client. As for the time inbetween, just change your docker command to have this in: `factoriotools/factorio:1.1.21`

**Comment by SuperSandro2000** [comment] 2021-02-21 06:07
Duplicate of #368

**Closed by SuperSandro2000** 2021-02-21 06:07 UTC
