### ISSUE TITLE
Version Mismacth 1.1.33 is tagged as 'stable'

### ISSUE THREAD

**Issue by Mangnoppa** [factoriotools/factorio-docker#390] opened 2021-05-04 10:41 UTC
The tag `stable` references the `latest` tag, which was true for version 1.1.32 but 1.1.33 is the new `latest` and 1.1.32 stays `stable`

**Comment by Fank** [comment] 2021-05-04 11:41
Duplicate of #383

**Closed by Fank** 2021-05-04 11:41 UTC
