### ISSUE TITLE
Pulling the latest version still returns old version

### ISSUE THREAD

**Issue by nev4ever** [factoriotools/factorio-docker#355] opened 2021-01-14 20:31 UTC
The latest version should be 1.1.11.

But I get this:
--start-server-load-latest
   0.000 2021-01-14 20:09:55; Factorio 1.1.10 (build 57667, linux64, headless)

**Comment by bplein** [comment] 2021-01-14 20:55
The 1.1.11 build is failing.

**Comment by CyrielRct** [comment] 2021-01-14 22:17
Having same issue.

**Comment by aarontc** [comment] 2021-01-15 03:46
Same issue here. The travis log indicates dockerhub is ratelimiting the build.

**Comment by SuperSandro2000** [comment] 2021-01-15 09:36
Duplicate of #354

**Closed by SuperSandro2000** 2021-01-15 09:36 UTC
