### ISSUE TITLE
Mod mismatch error on 2.0.9 

### ISSUE THREAD

**Issue by Elmani335** [factoriotools/factorio-docker#528] opened 2024-10-23 14:54 UTC
Hello ! 

Just did the latest update on the service side, and now the client can no more connect, saying "mod mismatch"
![factorio_mgEX6CZqd4](https://github.com/user-attachments/assets/91c991ac-97d8-41c9-84e3-579faf34cec8)
![factorio_yaoi0epYWj](https://github.com/user-attachments/assets/9ab5d007-4c44-4225-b51e-912cc683c25e)

I tried to update to the "stable" version with this command :
`sudo docker pull factoriotools/factorio:stable`
_(I did the stop and rm commands before)_

but it doesn't seem to be fixing the issue, any idea ? thx !

here some (I guess) interesting part of the logs ?

```
0.036 Loading mod core 0.0.0 (data.lua)
   0.067 Loading mod base 2.0.9 (data.lua)
   0.449 Loading mod elevated-rails 2.0.9 (data.lua)
   0.561 Loading mod quality 2.0.9 (data.lua)
   0.588 Loading mod space-age 2.0.9 (data.lua)
   1.233 Loading mod base 2.0.9 (data-updates.lua)
   1.285 Loading mod quality 2.0.9 (data-updates.lua)
   1.409 Loading mod space-age 2.0.9 (data-updates.lua)
   1.680 Checksum for core: 2820763882
   1.680 Checksum of base: 1355320214
   1.680 Checksum of elevated-rails: 1891730324
   1.680 Checksum of quality: 3715527832
   1.680 Checksum of space-age: 440491908
   2.622 Prototype list checksum: 984080119
   2.785 Info PlayerData.cpp:66: Local player-data.json available, timestamp 1729457228
   2.785 Info PlayerData.cpp:73: Cloud player-data.json unavailable
   2.789 Factorio initialised
   2.790 Info ServerSynchronizer.cpp:20: nextHeartbeatSequenceNumber(0) initialized Synchronizer nextTickClosureTick(0).
   2.790 Info ServerMultiplayerManager.cpp:803: updateTick(18446744073709551615) changing state from(Ready) to(PreparedToHostGame)
   2.790 Info ServerMultiplayerManager.cpp:803: updateTick(18446744073709551615) changing state from(PreparedToHostGame) to(CreatingGame)
   2.791 Loading map /factorio/saves/_autosave1.zip: 9641614 bytes.
   2.831 Loading level.dat: 27087746 bytes.
   2.844 Info Scenario.cpp:178: Map version 1.1.110-0
   2.858 Info PrototypeMigrationList.cpp:197: Activating migration base/1.2.0 stack inserter rename.json
   2.858 Info PrototypeMigrationList.cpp:197: Activating migration base/2.0.0-biter-egg.json
   2.858 Info PrototypeMigrationList.cpp:197: Activating migration base/2.0.0-internal.json
   2.858 Info PrototypeMigrationList.cpp:197: Activating migration base/2.0.0-internal2.json
   2.858 Info PrototypeMigrationList.cpp:197: Activating migration base/2.0.0-internal3.json
   2.858 Info PrototypeMigrationList.cpp:197: Activating migration base/2.0.0.json
   2.858 Info PrototypeMigrationList.cpp:197: Activating migration space-age/aquilo-tilesets.json
   2.858 Info PrototypeMigrationList.cpp:197: Activating migration space-age/biolab.json
   2.858 Info PrototypeMigrationList.cpp:197: Activating migration space-age/internal.json
   2.859 Info PrototypeMigrationList.cpp:197: Activating migration space-age/jelly-yum-rename.json
   2.859 Info PrototypeMigrationList.cpp:197: Activating migration space-age/shattered-planet.json
   2.859 Info PrototypeMigrationList.cpp:197: Activating migration space-age/tungsten-belt-rename.json
   4.080 Info ItemStack.cpp:271: Fixing non-stackable ItemStack count from 11 to 1 for: pointer: 0x000074b0cfc21dc0, item pointer: (nil), ID: 318, count: 11, stack size: 1, prototype stack size: 1, prototype type: item.
   4.080 Info ItemStack.cpp:271: Fixing non-stackable ItemStack count from 10 to 1 for: pointer: 0x000074b0cfc21dd8, item pointer: (nil), ID: 317, count: 10, stack size: 1, prototype stack size: 1, prototype type: item.
   4.445 Blueprint storage "blueprint-storage-2.dat" was not found, trying to load previous version storage "blueprint-storage.dat"
   5.521 Loading script.dat: 1182 bytes.
```

**Comment by Fank** [comment] 2024-10-23 15:16
Duplicate of #526

**Closed by Fank** 2024-10-23 15:16 UTC
