### ISSUE TITLE
Incorrect loading of the stable tag version

### ISSUE THREAD

**Issue by BadWolf1st** [factoriotools/factorio-docker#527] opened 2024-10-23 12:24 UTC
I created a docker compose file and set the stable tag. **I expected to download version 2.0.9** (currently listed in the readme and website Factorio.com as stable). But instead, when using the **docker compose pull** command, **I get version 2.0.8**

What am I doing wrong?

My compose file:
![image](https://github.com/user-attachments/assets/d5cca7c0-0943-41ab-8e78-4808999c46fd)

What game say me:
![image](https://github.com/user-attachments/assets/abcde22b-215e-4c9d-b671-36773e0ff550)
Translate:
A version mismatch has been detected!
An older version of the game is installed on the server.
Your version: 2.0.9.
Server version: 2.0.8.

**Comment by Kegath** [comment] 2024-10-23 13:25
There seems to be an issue with the stable branch at the moment. Use factoriotools/factorio:2.0.9 to force 2.0.9 on the server

**Comment by BadWolf1st** [comment] 2024-10-23 14:56
> There seems to be an issue with the stable branch at the moment. Use factoriotools/factorio:2.0.9 to force 2.0.9 on the server

The problem is that together with the factorio container, I use the watchtower container, which in theory should force the factorio container to load a newer version from the stable branch

**Comment by Fank** [comment] 2024-10-23 15:17
Duplicate of #526

**Closed by Fank** 2024-10-23 15:17 UTC
