### ISSUE TITLE
Permission Denied on /opt/factorio/saves

### ISSUE THREAD

**Issue by Floopy-Doo** [factoriotools/factorio-docker#190] opened 2019-02-27 19:17 UTC
I could use some help while setting up the docker image. I did use your docker image for 0.16 and i didnt have those problems but i cant get it to work for 0.17.

I get a permission denied whenever I start the docker container for factorio.
I crash with the error `Util.cpp:75: filesystem error: status: Permission denied [/opt/factorio/saves]`

I have set up the client as follows: 
`sudo docker pull dtandersen/factorio:0.17

sudo docker run -d \
-p 34198:34197/udp \
-p 27016:27015/tcp \
-v /volume1/GameInstances/factorio_map017:/factorio:Z \
--name factorio2 \
dtandersen/factorio:0.17`

I changed the chown of the /volume1/GameInstances/factorio_map017 to 845:845
I let the container run in high privilege mode.
I tried the Z at the end.

Nothing worked so far. Has someone an idea where I might have done something wrong?

[errorlog_factorio2.txt](https://github.com/dtandersen/docker_factorio_server/files/2911911/errorlog_factorio2.txt)

**Comment by dtandersen** [comment] 2019-02-27 19:50
You can try `0.17.2-2`. I think maybe the map generator created some files as root.

https://github.com/dtandersen/docker_factorio_server/commit/8e7bca222ae57333afcee7390ffaad683e537f27

**Comment by Floopy-Doo** [comment] 2019-02-27 20:22
just tried it, its still the same.
i have no idea from where the container gets the /opt/factorio/saves...

**Comment by dtandersen** [comment] 2019-02-27 20:42
You can use this to see:

```
[vagrant@docker 0.17]$ docker run --rm -it --entrypoint /bin/sh dtandersen/factorio:0.17.2-2
/ # cd /opt/factorio/
/opt/factorio # ls -al
total 20
drwxrwxrwx    4 factorio factorio      4096 Feb 27 19:57 .
drwxr-xr-x    1 root     root          4096 Feb 27 19:57 ..
drwxr-xr-x    3 factorio factorio      4096 Feb 27 19:57 bin
-rw-r--r--    1 factorio factorio       998 Jan 16  2018 config-path.cfg
drwxr-xr-x    4 factorio factorio      4096 Feb 27 19:57 data
lrwxrwxrwx    1 factorio factorio        14 Feb 27 19:57 mods -> /factorio/mods
lrwxrwxrwx    1 factorio factorio        15 Feb 27 19:57 saves -> /factorio/saves
lrwxrwxrwx    1 factorio factorio        19 Feb 27 19:57 scenarios -> /factorio/scenarios
lrwxrwxrwx    1 factorio factorio        23 Feb 27 19:57 script-output -> /factorio/script-output
```

**Comment by SuperSandro2000** [comment] 2019-05-05 01:28
duplicate of #173

**Closed** 2019-05-16 18:08 UTC
Labels: bug, duplicate
