### ISSUE TITLE
Stable downloads 1.1.24

### ISSUE THREAD

**Issue by Wumfie** [factoriotools/factorio-docker#374] opened 2021-02-17 16:38 UTC
According to their website, the stable release is 1.1.21 which is what my game is running from steam. I am on the "stable" version of the docker and it downloaded 1.1.24 upon update.

**Comment by SuperSandro2000** [comment] 2021-02-17 22:01
Duplicate of #368

**Closed by SuperSandro2000** 2021-02-17 22:01 UTC

**Comment by Wumfie** [comment] 2021-02-19 15:10
game is now on 1.1.25 so no longer an issue
